<script setup lang="ts">
</script>

<template>
  <div class="tos animate__animated animate__fadeIn">
    <div class="container">
      <div class="box">
        <div class="header">
          <h1 class="title is-4 is-marginless">Kolibri Terms Of Service</h1>
        </div>
        <div class="columns is-marginless">
          <div class="column">
            <div class="docs-content content">

              <p class="c0"><span>Updated: Feb 01, 2021</span></p>
              <h2 class="c16" id="h.lzbj8t8w1g1v"><span class="c17">Terms of Service</span></h2>
              <p class="c0"><span>This agreement (&ldquo;Agreement&rdquo;) is between you (&ldquo;your,&rdquo; &ldquo;U</span><span class="c10">ser,&rdquo; or, &ldquo;Users&rdquo;) and Hover Labs LLC., a company organized under the laws of the State of Delaware (&ldquo;Company,&rdquo; &ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;) (together with you, the &ldquo;Parties&rdquo;) concerning your use of (including any access to) Company&rsquo;s websites, currently located at kolibri.finance, mobile applications, web applications, decentralized applications, smart contracts and APIs located at any of Company&rsquo;s websites (together with any materials and services available therein, and successor website(s) or application(s) thereto, the &ldquo;Site&rdquo;). This Agreement hereby incorporates by this reference any additional terms and conditions with respect to the Site posted by Company to the Site, or otherwise made available to you by Company.</span></p>
              <p class="c0 c11"><span class="c1"></span></p>
              <p class="c0"><span class="c5">By clicking or tapping any button or box marked &ldquo;accept&rdquo; or &ldquo;agree&rdquo; (or a similar term) in connection with this Agreement, or by accessing or using the Site or the Services (as defined below), you agree to be bound by this Agreement, a current version of which is available at the Site, and which may be modified from time to time at our sole discretion in accordance with section 3 below.</span></p>
              <p class="c0 c11"><span class="c5"></span></p>
              <h2 class="c3" id="h.hmg3rnnuxn4i"><span class="c8">1. Use of Services</span></h2>
              <h3 class="c2" id="h.13ilr2qg2xxo"><span class="c9">1.1. Services</span></h3>
              <p class="c4"><span class="c5">The Company has developed Kolibri &ndash; an online, decentralized and autonomous environment that displays price information and autonomous smart contract mechanisms of digital tokens and assets (&ldquo;Digital Assets&rdquo;). The Company also provides a user interface that guides your access to Kolibri, and may update the protocol underlying Kolibri from time to time (the &ldquo;Services&rdquo;).</span></p>
              <p class="c4"><span class="c10">You affirm that you are aware and acknowledge that Company is primarily a provider of software-based services. Company does not intend to custody, control or manage funds in any manner whatsoever. </span><span class="c10">Kolibri i</span><span class="c5">s deployed in a decentralized environment and it can be autonomously and directly accessed by the Users without use of our interface.</span></p>
              <h3 class="c2" id="h.9k1vhs4xnhrs"><span class="c9">1.2. Your Use of Services</span></h3>
              <p class="c4"><span class="c5">You represent and warrant to Company that:</span></p>
              <ul class="c12 lst-kix_v5xxe9sh1d70-0 start">
                <li class="c6 li-bullet-0"><span class="c5">You are eligible to enter into the Agreement and use the Services in accordance with section 2 below.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">This Agreement is valid, and binding on you, and enforceable against you.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">You will comply with all terms and conditions of this Agreement.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">You acknowledge and agree that from time to time the Site may be inaccessible or inoperable for any reason, including, without limitation: (i) equipment malfunctions; (ii) periodic maintenance procedures or repairs which Company may undertake from time to time; (iii) causes beyond the control of Company or which are not reasonably foreseeable by Company; (iv) disruptions and temporary or permanent unavailability of the underlying blockchain infrastructure; (v) unavailability of third party service providers or external partners for any reason. In this case, you may be prevented from accessing or using the Services.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">You acknowledge and agree that the Site and the Services may evolve over time. This means Company may apply changes, replace, or discontinue (temporarily or permanently) the Services at any time in Company&rsquo;s sole discretion.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">You acknowledge and agree that the pricing information provided on the Site does not represent an offer, a solicitation of an offer, or any advice regarding, or recommendation to enter into, a transaction with Company.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">You acknowledge and agree that the Company does not act as an agent for any of the Users.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">You are solely responsible for your use of the Services, including all transfers of Digital Assets you make.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">In connection with using the Services, you will only transfer legally-obtained Digital Assets that belong to you.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">You will obey all applicable laws in connection with using the Services. You will not use the Site or the Services if the laws of your country, or any other applicable law, prohibit you from doing so in accordance with this Agreement.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">You are solely responsible for reporting and paying any taxes applicable to your use of the Services.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">You are not and have not been placed on any excluded or denied persons lists by any authority.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">You are responsible for complying with any applicable export controls or embargoes.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">Any Digital Assets used by you in connection with the Services are either owned by you or that you are validly authorized to carry out actions using such Digital Assets.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">You acknowledge and agree that we have no control over, or liability for, the delivery, quality, safety, legality or any other aspect of any Digital Assets that you may transfer to or from a third party, and that we are not responsible for ensuring that an entity with whom you transact actually completes the transaction or is authorized to do so. If you experience a problem with any Digital Assets purchased from or sold to a third party through the Services, you bear the entire risk.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">You covenant that all activity and conduct in connection with your use of the Services, including any resultant transactions of the Digital Assets, will be in compliance with all applicable law, rules, regulations, requirements, guidelines and policies of any governmental or quasi-governmental body or regulatory agency, any self-regulatory organization.</span></li>
                <li class="c6 li-bullet-0"><span class="c10">You are not a resident of any of the following countries or regions: Belarus, Burma (Myanmar), Burundi, Central African Republic, Congo, C&ocirc;te d'Ivoire, Cuba, Iran, Iraq, Lebanon, Liberia, Libya, Mali, Nicaragua, North Korea, Somalia, South Sudan, Sudan, Syria, Crimea (Ukraine/Russia), Venezuela, Yemen, Zimbabwe (&ldquo;Non-Supported Countries&rdquo;).</span></li>
                <li class="c6 li-bullet-0"><span class="c5">You do not use Virtual Private Network software or any other privacy or anonymization tools or techniques in order to circumvent any restrictions which apply to the Services, especially those which restrict the geographical availability of the Services.</span></li>
              </ul>
              <h3 class="c2" id="h.jn0ljip9q9ao"><span class="c9">1.3. Fees</span></h3>
              <p class="c4"><span class="c10">Company does not charge any fees for use of Services. However, in connection with your use of the Kolibri mainnet, you acknowledge the existence of fees and costs necessary to conduct transactions. A list of fees related to the Kolibri mainnet can be found at </span><span class="c10 c13">https://kolibri.finance/project-info/general/fees</span><span class="c10">. We attempt to provide accurate costs information regarding your use of the Kolibri mainnet, but this information is subject to change quickly, without notice to us, and will remain outside of our control; please carefully review the disclosed fees prior to engaging in any Kolibri mainnet transaction.</span></p>
              <h2 class="c3" id="h.l7r76or6gnb"><span class="c8">2. Eligibility</span></h2>
              <p class="c4"><span class="c5">You affirm that you are of legal age to enter into this Agreement where you live, that you are at least 18 years of age or older, and have the legal capacity to enter into this Agreement, as well as that you are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations and warranties set forth in this Agreement and to abide by and comply with this Agreement.</span></p>
              <p class="c4"><span class="c5">If you are an individual accessing or using the Site on behalf of, or for the benefit of, any corporation, partnership or other entity with which you are associated (an &ldquo;Organization&rdquo;), then you are agreeing to this Agreement on behalf of yourself and such Organization, and you represent and warrant that you have the legal authority to bind such Organization to this Agreement. References to &ldquo;you&rdquo; and &ldquo;your&rdquo; in this Agreement will refer to both the individual using the Site and to any such Organization.</span></p>
              <p class="c4"><span class="c5">You represent that you are legally permitted to use the Services in your jurisdiction including owning Digital Assets, and interacting with the Services in any way. You further represent you are responsible for ensuring compliance with the laws of your jurisdiction and acknowledge that Company is not liable for your compliance with such laws. You further represent and warrant that you will not use the Site or the Services if the laws of your country of residency or establishment prohibit you from doing so in accordance with this Agreement. You further represent that neither you nor your Organization is a resident of any of the Non-Supported Countries. Finally, you represent and warrant that you will not use the Services for any illegal activity.</span></p>
              <h2 class="c3" id="h.4l6r3dagdcxc"><span class="c8">3. Modification of Agreement and Transfer</span></h2>
              <p class="c4"><span class="c5">This Agreement may be discretionarily modified or replaced at any time, unless stated otherwise herein. The most current version of this Agreement will be posted on the Site with the &ldquo;Last Revised&rdquo; date at the top of the Agreement changed. Any changes or modifications will be effective immediately upon posting the revisions to the Site. You shall be responsible for reviewing and becoming familiar with any such modifications. You waive any right you may have to receive specific notice of such changes or modifications. Use of the Site or the Services by you after any modification to the Agreement constitutes your acceptance of the Agreement as modified. If you do not agree to the Agreement in effect when you access or use the Services, you must stop using the Services. We may, at any time and without liability or prior notice, modify or discontinue all or part of the Site (including access to the Site via any third-party links). Neither party may assign or transfer any rights or obligations under this Agreement, provided that Company may assign this Agreement without your prior consent to any of Company&rsquo;s affiliates, or to its successors in interest of any business associated with the Services provided by Company. This Agreement shall be binding upon the permitted assigns or transferees of each party.</span></p>
              <h2 class="c3" id="h.zhedw8vxm81k"><span class="c8">4. Representations, Warranties, and Risks</span></h2>
              <h3 class="c2" id="h.42jnexjirqxp"><span class="c9">4.1. No Representation or Warranty</span></h3>
              <p class="c4"><span class="c5">You expressly understand and agree that your use of the Service is at your sole risk.</span></p>
              <p class="c4"><span class="c5">WE MAKE AND EXPRESSLY DISCLAIM ALL REPRESENTATIONS AND WARRANTIES, EXPRESS, IMPLIED OR STATUTORY, AND WITH RESPECT TO THE SERVICES AND THE CODE PROPRIETARY OR OPEN SOURCE, WE SPECIFICALLY DO NOT REPRESENT AND WARRANT AND EXPRESSLY DISCLAIM ANY REPRESENTATION OR WARRANTY, EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION, ANY REPRESENTATIONS OR WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY, USAGE, SECURITY, SUITABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE, OR AS TO THE WORKMANSHIP OR TECHNICAL CODING THEREOF, OR THE ABSENCE OF ANY DEFECTS THEREIN, WHETHER LATENT OR PATENT. WE DO NOT REPRESENT OR WARRANT THAT THE SERVICES, CODE AND ANY RELATED INFORMATION ARE ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE.</span></p>
              <h3 class="c2" id="h.luvtq99gdwzi"><span class="c9">4.2. Disclaimer of Fiduciary Duties</span></h3>
              <p class="c4"><span class="c5">To the fullest extent permitted by law and notwithstanding any other provision of this Agreement or any other agreement contemplated herein or applicable provisions of law or equity or otherwise, the parties hereto hereby agree to eliminate any and all fiduciary duties Company may have to the user, its affiliates, or the end users of the Services, the site or its content, provided that such exclusion or limitation of liability shall not extend to the Company&rsquo;s misappropriation of assets or funds of its users or its affiliates, or the end users of the Services, Site or content provided by Company or other acts or omissions that constitute a bad faith violation of the implied contractual covenant of good faith and fair dealing.</span></p>
              <h3 class="c2" id="h.ujgbbcgbzjie"><span class="c9">4.3 Sophistication and Risk of Cryptographic Systems</span></h3>
              <p class="c4"><span class="c5">By utilizing the Services or interacting with the Site in any way, you represent that you understand the inherent risks associated with cryptographic systems; and warrant that you have an understanding of the usage and intricacies of native cryptographic tokens such as Tezos (XTZ) and Bitcoin (BTC), smart contract based tokens such as those that follow the Tezos FA1.2 Token Standard (https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-7/tzip-7.md), and blockchain-based software systems.</span></p>
              <p class="c4"><span class="c5">The Company does not own or control any of the underlying software through which blockchain networks are formed. In general, the underlying software for blockchain networks tends to be open source such that anyone can use, copy, modify, and distribute it. By using the Services, you acknowledge and agree (i) that Company is not responsible for operation of the underlying software for any blockchain network or for the networks themselves, that there exists no guarantee of functionality, security, or availability of such software and networks; and (ii) that the underlying protocols are subject to sudden changes in operating rules (known as &ldquo; Forks &rdquo;), and that such Forks may materially affect the Services. It might be discretionarily decided not to support (or cease supporting) the Forked network entirely. You acknowledge and agree that Company assumes absolutely no responsibility whatsoever in respect of any underlying software protocols, whether Forked or not.</span></p>
              <p class="c4"><span class="c5">Underlying networks use public/private key cryptography. You alone are responsible for securing your private key(s). Company does not have access to your private key(s). Losing control of your private key will permanently and irreversibly deny you access to funds on the Tezos blockchain or other network. Neither Company nor any other person will be able to retrieve or protect your Digital Assets or funds. Once your private key(s) is lost, you will not be able to transfer your Digital Assets to any other address or wallet. If this occurs, you will not be able to realize any value or utility that you may hold now or in future.</span></p>
              <h3 class="c2" id="h.lpyt88rpmudc"><span class="c9">4.4 Risk of Regulatory Actions in One or More Jurisdictions</span></h3>
              <p class="c4"><span class="c5">The Services, Digital Assets and XTZ could be impacted by one or more regulatory inquiries or regulatory action, which could impede or limit the ability of Company to continue to develop, or which could impede or limit your ability to access or use the Services or Tezos blockchain, including access to your Digital Assets or other funds.</span></p>
              <h3 class="c2" id="h.99w6dw73m121"><span class="c9">4.5 Risk of Weaknesses or Exploits in the Field of Cryptography</span></h3>
              <p class="c4"><span class="c10">You acknowledge and understand that Cryptography is a progressing field. Advances in code cracking or technical advances such as the development of quantum computers may present risks to cryptocurrencies, Digital Assets and Services, which could result in the theft or loss of your Digital Assets or property. </span><span class="c10">To the extent possible, </span><span class="c10">we intend </span><span class="c10">to update the protocol underlying the </span><span class="c10">Kolibri mainnet </span><span class="c10">to account for any advances in cryptography and to incorporate additional security measures, but </span><span class="c10">do</span><span class="c10">&nbsp;not guarantee or otherwise represent full security of the system.</span><span class="c5">&nbsp;By using the Services or accessing the Site, you acknowledge these inherent risks.</span></p>
              <h3 class="c2" id="h.6icu1e490bxo"><span class="c9">4.6 Volatility of Cryptocurrency</span></h3>
              <p class="c4"><span class="c10">You understand that Tezos and other blockchain technologies and associated Digital Assets, currencies or tokens are highly volatile due to many factors including but not limited to adoption, speculation, technology and security risks. You also acknowledge that the cost of transacting on such technologies is variable and may increase at any time causing impact to any activities taking place on the Tezos blockchain. </span><span class="c15">You acknowledge that the cost and speed of transacting with cryptographic and blockchain-based systems such as Tezos are variable and may increase dramatically at any time.</span></p>
              <p class="c4"><span class="c10">We have developed kUSD as a self-balancing algorithmic stablecoin. However, such a stablecoin may fail to work as intended, or depend on forces outside our control, which may negatively affect kUSD and its entire ecosystem.</span><span class="c5">&nbsp;Due to a variety of factors outside of Company's control, the value of kUSD, particularly on third-party platforms such as cryptocurrency exchange platforms, can fluctuate above or below one U.S. Dollar. The Company is not responsible for any losses incurred as a result of using the system.</span></p>
              <p class="c4"><span class="c5">You acknowledge these risks and represent that Company cannot be held liable for such fluctuations or increased costs.</span></p>
              <h3 class="c2" id="h.rn0c6yppsavk"><span class="c9">4.7 Application Security</span></h3>
              <p class="c4"><span class="c5">You acknowledge that the Services are subject to flaws and acknowledge that you are solely responsible for evaluating any code provided by the Services or Site. This warning and others provided in this Agreement by Company in no way evidence or represent an ongoing duty to alert you to all of the potential risks of utilizing the Services or accessing the Site.</span></p>
              <h3 class="c2" id="h.5f8z621q8jq"><span class="c9">4.8 Site Accuracy</span></h3>
              <p class="c4"><span class="c5">Although it is intended to provide accurate and timely information on the Site, the Site or relevant tools may not always be entirely accurate, complete or current and may also include technical inaccuracies or typographical errors. In an effort to continue to provide you with as complete and accurate information as possible, information may be changed or updated from time to time without notice, including, without limitation, information regarding our policies. Accordingly, you should verify all information before relying on it, and all decisions based on information contained on the Site or relevant tools are your sole responsibility and Company shall have no liability for such decisions. Links to third-party materials (including, without limitation, websites) may be provided as a convenience but are not controlled by any entity. You acknowledge and agree that we are not responsible for any aspect of the information, content, or services contained in any third-party materials or on any third party sites accessible or linked to the Site or available via other relevant tools.</span></p>
              <p class="c4"><span class="c5">No representation is made as to the accuracy, completeness or appropriateness for any particular purpose of any pricing information distributed via the Site. Prices and pricing information may be higher or lower than prices available on other platforms.</span></p>
              <h3 class="c2" id="h.dgs8bnafq7o5"><span class="c9">4.9 Technical Knowledge</span></h3>
              <p class="c4"><span class="c5">Any use or interaction with the Services requires a comprehensive understanding of applied cryptography and computer science in order to appreciate the inherent risks, including those listed above. You represent and warrant that you possess relevant knowledge and skills. Any reference to a type of Digital Asset on the Site does not indicate our approval or disapproval of the underlying technology regarding such type of Digital Asset, and should not be used as a substitute for your own understanding of the risks specific to each type of Digital Asset. We make no warranty as to the suitability of the Digital Assets referenced on the Site and assume no fiduciary duty in our relations with you.</span></p>
              <h3 class="c2" id="h.uwlad5jte73d"><span class="c9">4.10 Financial Risks</span></h3>
              <p class="c4"><span class="c5">Use of the Services may carry financial risk. Digital Assets are, by their nature, highly experimental, risky, volatile and transactions carried through the Services are irreversible, final and there are no refunds. You acknowledge and agree that you will access and use the Site and the Services at your own risk. The risk of loss can be substantial. You should, therefore, carefully consider whether the Services are suitable for you in light of your circumstances and financial resources. By using the Services, you represent that you have been, are and will be solely responsible for making your own independent appraisal and investigations into the risks of a given transaction and the underlying Digital Assets. You represent that you have sufficient knowledge, market sophistication, professional advice and experience to make your own evaluation of the merits and risks of any transaction conducted via the Services or any underlying Digital Asset. You accept all consequences of using the Services, including the risk that you may lose access to your Digital Assets indefinitely. All transaction decisions are made solely by you. Notwithstanding anything in this Agreement, we accept no responsibility whatsoever for, and will in no circumstances be, liable to you in connection with the use of the Services for performing Digital Asset transactions. Under no circumstances will the operation of all or any portion of the Site or the Services be deemed to create a relationship that includes the provision or tendering of investment advice.</span></p>
              <h3 class="c2" id="h.f7bj2o66c7k"><span class="c9">4.11 Applicable Law and Tax</span></h3>
              <p class="c4"><span class="c5">You are responsible for complying with applicable law. You agree that we are not responsible for determining whether or which laws may apply to your use of Services, including tax laws. You are solely responsible for reporting and paying any taxes arising from your use of the Site and Services.</span></p>
              <p class="c4"><span class="c5">Company must comply with applicable law. Applicable law, regulation, and executive orders may require us to, upon request by government agencies, take certain actions or provide information.</span></p>
              <h3 class="c2" id="h.czc2pppj008v"><span class="c9">4.12 Operational Risks</span></h3>
              <p class="c4"><span class="c5">You are aware of and accept the risk of operational challenges. The Site may experience sophisticated cyber attacks, unexpected surges in activity or other operational or technical difficulties that may cause interruptions to or delays on the Site. You agree to accept the risk of the Services failure resulting from unanticipated or heightened technical difficulties, including those resulting from sophisticated attacks, and you agree not to hold us accountable for any related losses. We will not bear any liability, whatsoever, for any damage or interruptions caused by any viruses that may affect your computer or other equipment, or any phishing, spoofing or other attack. We advise the regular use of a reputable and readily available virus screening and prevention software. We do not guarantee that the Site is or will remain updated, complete, correct or secure, or that access to the Site will be uninterrupted. The Site may include inaccuracies, errors and materials that violate or conflict with this Agreement. Additionally, third parties may make unauthorized alterations to the Site or the software underlying the Services. Accordingly, you should verify all information on the Site before relying on it, and all decisions based on information contained on the Site are your sole responsibility and we will have no liability for such decisions.</span></p>
              <h2 class="c3" id="h.p4j38dkohj3g"><span class="c8">5. Indemnity</span></h2>
              <p class="c4"><span class="c5">You agree to release and to indemnify, defend and hold harmless Company, as well as its officers, directors, employees and representatives, from and against any and all losses, liabilities, expenses, damages, costs (including attorneys&rsquo; fees, fees or penalties imposed by any regulatory authority and court costs) claims or actions of any kind whatsoever arising or resulting from your use of the Services, your violation of this Agreement, your violation of any law, rule, or regulation, or the rights of any third party, and any of your acts or omissions that implicate publicity rights, defamation or invasion of privacy. Company reserves the right, at its own expense, to assume exclusive defense and control of any matter otherwise subject to indemnification by you and, in such case, you agree to cooperate with Company in the defense of such matter.</span></p>
              <h2 class="c3" id="h.mt3avd44vzh5"><span class="c8">6. Limitation on Liability</span></h2>
              <p class="c4"><span class="c5">You acknowledge and agree that you assume full responsibility for your use of the Site and Services. You acknowledge and agree that any information you send or receive during your use of the Site and Services may not be secure and may be intercepted or later acquired by unauthorized parties. You acknowledge and agree that your use of the Site and Service is at your own risk. Recognizing such, you understand and agree that, to the fullest extent permitted by applicable law, neither Company nor any related entities, suppliers or licensors will be liable to you for any direct, indirect, incidental, special, consequential, punitive, exemplary or other damages of any kind, including without limitation damages for loss of profits, goodwill, use, data or other tangible or intangible losses or any other damages based on contract, tort, strict liability or any other theory (even if Company had been advised of the possibility of such damages), resulting from the Site or Services; the use or the inability to use the Site or Service; unauthorized access to or alteration of your transmissions or data; statements or conduct of any third party on the Site or Service; any actions we take or fail to take as a result of communications you send to us; human errors; technical malfunctions; failures, including public utility or telephone outages; omissions, interruptions, latency, deletions or defects of any device or network, providers, or software (including, but not limited to, those that do not permit participation in the service); any injury or damage to computer equipment; inability to fully access the site or service or any other website; theft, tampering, destruction, or unauthorized access to, images or other content of any kind; data that is processed late or incorrectly or is incomplete or lost; typographical, printing or other errors, or any combination thereof; or any other matter relating to the Site or Service.</span></p>
              <p class="c4"><span class="c5">Some jurisdictions do not allow the exclusion of certain warranties or the limitation or exclusion of liability for incidental or consequential damages. accordingly, some of the above limitations may not apply to you.</span></p>
              <h2 class="c3" id="h.5vo53y2mmslv"><span class="c8">7. Open Source and Proprietary Rights</span></h2>
              <p class="c4"><span class="c10">Some software used in our Services may be offered under an open source license that we will make available to you. Documentation of open source code is available on the </span><span class="c10 c18"><a class="c7" href="https://github.com/hover-labs">Hover Labs</a></span><span class="c10">&nbsp;page. This documentation, including any code shown in it, is licensed under the</span><span class="c10">&nbsp;</span><span class="c18 c10"><a class="c7" href="https://opensource.org/licenses/MIT">MIT License</a></span><span class="c10">&nbsp;</span><span class="c5">and you agree to abide by the terms of this license.</span></p>
              <p class="c4"><span class="c5">The &ldquo;Kolibri&rdquo; name, the Kolibri logo, other related trademarks (&ldquo;Kolibri DeFi,&rdquo; &ldquo;kUSD&rdquo;), and the web domains and URLs are property of Hover Labs. Using our Services does not give you ownership of any proprietary intellectual property rights in our Services or the content you access. You may not use proprietary content from our Services unless you obtain permission from its owner or are otherwise permitted by law. These terms do not grant you the right to use any branding or logos used in our Services. You may not remove, obscure, or alter any legal notices displayed in or along with our Services.</span></p>
              <h2 class="c3" id="h.jgqozdu638s0"><span class="c8">8. Links</span></h2>
              <p class="c4"><span class="c5">The Service provides, or third parties may provide, links to other World Wide Web or accessible sites, applications or resources. You authorize the Company to provide certain personal data and information, including any data as described and addressed in the Privacy Policy. You acknowledge and agree that Company is not responsible for the availability of any external sites, applications or resources provided by third parties, and does not endorse and is not responsible or liable for any content, advertising, products or other materials on or available from sites or resources offered by third parties. You further acknowledge and agree that Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such site or resource.</span></p>
              <h2 class="c3" id="h.l0ilcf21ed6g"><span class="c8">9. Termination and Suspension</span></h2>
              <p class="c4"><span class="c5">Company may terminate or suspend all or part of the Site and/or Services access immediately, without prior notice or liability, if you breach any of the terms or conditions of the Agreement. Upon termination of your access, your right to use the Services will immediately cease. The following provisions of the Agreement survive any termination of these Agreement: INDEMNITY; REPRESENTATIONS, WARRANTIES AND RISKS; LIMITATION ON LIABILITY; OUR PROPRIETARY RIGHTS; LINKS; TERMINATION; NO THIRD-PARTY BENEFICIARIES; ARBITRATION AND CLASS ACTION WAIVER; USE OF SERVICES.</span></p>
              <h2 class="c3" id="h.au0peiskrcad"><span class="c8">10. No Third-Party Beneficiaries</span></h2>
              <p class="c4"><span class="c5">You agree that, except as otherwise expressly provided in this Agreement, there shall be no third party beneficiaries to the Agreement.</span></p>
              <h2 class="c3" id="h.gp0l2uegssro"><span class="c8">11. Arbitration and Class Action Waiver</span></h2>
              <h3 class="c2" id="h.dknuwsqeyqj2"><span class="c9">11.1 Initial Dispute Resolution</span></h3>
              <p class="c4"><span class="c5">Please read the following section carefully because it requires you to arbitrate certain disputes with the Company and limits the manner in which you can seek relief from the Company.</span></p>
              <h3 class="c2" id="h.ca2e2y7t0rs7"><span class="c9">11.2 Binding Arbitration</span></h3>
              <p class="c4"><span class="c5">Except for disputes in which either party seeks to bring an individual action in small claims court or seeks injunctive or other equitable relief for the alleged unlawful use of copyrights, trademarks, trade names, logos, trade secrets or patents, you and the Company: (a) waive your right to have any and all disputes or claims arising from this Agreement or the Company (collectively, &ldquo;Disputes&rdquo;) resolved in a court; and (b) waive your right to a jury trial. Instead, you and the Company will arbitrate Disputes through binding arbitration (which is the referral of a Dispute to one or more persons charged with reviewing the Dispute and making a final and binding determination to resolve it, instead of having the Dispute decided by a judge or jury in court).</span></p>
              <h3 class="c2" id="h.ix98yt16sa82"><span class="c9">11.3. No Class Arbitrations, Class Actions or Representative Actions</span></h3>
              <p class="c4"><span class="c5">You and the Company agree that any dispute is personal to you and the Company and that any such dispute will be resolved solely through individual arbitration and will not be brought as a class arbitration, class action or any other type of representative proceeding. Neither party agrees to class arbitration or to an arbitration in which an individual attempts to resolve a dispute as a representative of another individual or group of individuals. Further, you and the Company agree that a dispute cannot be brought as a class, or other type of representative action, whether within or outside of arbitration, or on behalf of any other individual or group of individuals.</span></p>
              <h3 class="c2" id="h.9yclu2i8ogja"><span class="c9">11.4 Process</span></h3>
              <p class="c4"><span class="c10">You and the Company agree that you will notify each other in writing of any Dispute within thirty (30) days of when it arises so that the parties can attempt, in good faith, to resolve the Dispute informally. Notice to the Company shall be provided by sending an email to</span><span class="c10">&nbsp;legal@hover.engineering</span><span class="c10">. Your notice must include: (1) your name, postal address, and email address; (2) a description of the nature or basis of the Dispute; and (3) the specific relief that you are seeking. If you and the Company cannot agree how to resolve the Dispute within thirty (30) days of the Company receiving the notice, either you or Company may, as appropriate pursuant to this Section 11, commence an arbitration proceeding or file a claim in court. You and the Company agree that any arbitration or claim must be commenced or filed within one (1) year after the Dispute arose; otherwise, you and the Company agree that the claim is permanently barred (which means that you will no longer have the right to assert a claim regarding the Dispute). </span><span class="c10">You and the Company agree that: (a) any arbitration will occur in New York County, New York; (b) arbitration will be conducted confidentially by a single arbitrator in accordance with the rules of JAMS; and (c) the state or federal courts in New York will have exclusive jurisdiction over the enforcement of an arbitration award and over any Dispute between the parties that is not subject to arbitration. You may also litigate a Dispute in small claims court located in the county where you reside if the Dispute meets the requirements to be heard in small claims court.</span></p>
              <h3 class="c2" id="h.eho7a9csd9sc"><span class="c9">11.5. Authority of Arbitrator</span></h3>
              <p class="c4"><span class="c5">As limited by the FAA, this Agreement and applicable JAMS rules, the arbitrator will have: (a) the exclusive authority and jurisdiction to make all procedural and substantive decisions regarding a Dispute; and (b) the authority to grant any remedy that would otherwise be available in court. The arbitrator may only conduct an individual arbitration and may not consolidate more than one individual&rsquo;s claims, preside over any type of class or representative proceeding or preside over any proceeding involving more than one individual.</span></p>
              <h3 class="c2" id="h.kwn9bjd3dejs"><span class="c9">11.6. Rules of JAMS</span></h3>
              <p class="c4"><span class="c10">The rules of, and additional information about, JAMS are available on the JAMS website at </span><span class="c10"><a class="c7" href="http://www.jamsadr.com/">http://www.jamsadr.com/</a></span><span class="c5">, as may be updated from time to time. By agreeing to be bound by this Agreement, you either: (a) acknowledge and agree that you have read and understand the rules of JAMS; or (b) waive your opportunity to read the rules of JAMS and any claim that the rules of JAMS are unfair or should not apply for any reason.</span></p>
              <h3 class="c2" id="h.5ayqhvt86axi"><span class="c9">11.7 Governing law</span></h3>
              <p class="c4"><span class="c10">For any dispute not subject to arbitration you and Company agree to submit to the personal and exclusive jurisdiction of and venue in the federal and state courts located in New York County, New York. </span><span class="c5">You further agree to accept service of process by mail, and hereby waive any and all jurisdictional and venue defenses otherwise available. The Agreement and the relationship between you and Company shall be governed by the laws of the State of New York without regard to conflict of law provisions.</span></p>
              <h2 class="c3" id="h.64xcb9r0cvgh"><span class="c8">12. Prohibited Use</span></h2>
              <p class="c4"><span class="c5">You may not use the Service to engage in the following categories of activity ("Prohibited Uses"). The specific types of use listed below are representative, but not exhaustive. If you are uncertain as to whether or not your use of the Services involves a Prohibited Use, or have questions about how these requirements apply to you, please contact us at legal@hover.engineering. By using the Site or Services, you confirm that you will not use the Site or Services to do any of the following:</span></p>
              <ul class="c12 lst-kix_61rlfv18ubse-0 start">
                <li class="c6 li-bullet-0"><span class="c5">Unlawful Activity: Activity which would violate, or assist in violation of, any law, statute, ordinance, or regulation, sanctions programs administered in any relevant country, including but not limited to the U.S. Department of Treasury's Office of Foreign Assets Control ("OFAC"), or which would involve proceeds of any unlawful activity; publish, distribute or disseminate any unlawful material or information;</span></li>
                <li class="c6 li-bullet-0"><span class="c5">Abuse Other Users: Interfere with another individual's or entity's access to or use of any Services; defame, abuse, extort, harass, stalk, threaten or otherwise violate or infringe the legal rights (such as, but not limited to, rights of privacy, publicity and intellectual property) of others; incite, threaten, facilitate, promote, or encourage hate, racial intolerance, or violent acts against others; harvest or otherwise collect information from the Site about others, including without limitation email addresses, without proper consent;</span></li>
                <li class="c6 li-bullet-0"><span class="c5">Fraud: Activity which operates to defraud Company, other Users, or any other person; provide any false, inaccurate, or misleading information;</span></li>
                <li class="c6 li-bullet-0"><span class="c5">Intellectual Property Infringement: Engage in transactions involving items that infringe or violate any copyright, trademark, right of publicity or privacy or any other proprietary right under the law, including but not limited to sales, distribution, or access to counterfeit music, movies, software, or other licensed materials without the appropriate authorization from the rights holder; use of Company intellectual property, name, or logo, including use of Company trade or service marks, without express consent from Company or in a manner that otherwise harms Company; any action that implies an untrue endorsement by or affiliation with Company.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">Illegal Source of Funds: Use or accessing the Site or Services to transmit or exchange Digital Assets that are the direct or indirect proceeds of any criminal or fraudulent activity, including terrorism or tax evasion.</span></li>
                <li class="c6 li-bullet-0"><span class="c5">Other Prohibited Activities: Additionally, you confirm that you may not, nor may you assist other parties to:</span></li>
              </ul>
              <ul class="c12 lst-kix_61rlfv18ubse-1 start">
                <li class="c14 li-bullet-0"><span class="c5">attempt to disable or circumvent any security or access control mechanism of the Site or Services, where applicable;</span></li>
                <li class="c14 li-bullet-0"><span class="c5">design or assist in designing cheats, exploits, hacks, modes or any other unauthorized third-party software to modify or interfere with the Services, with the exception of automation software and bots, provided that such automation software and bots operate in the ordinary course of using the Services and do not cause disruption or harm to the Services;</span></li>
                <li class="c14 li-bullet-0"><span class="c5">institute, assist or become involved in any type of attack, including distribution of a virus, attacks upon the Services or the Site, that prevent access to or use of any of the above, other attempts to disrupt any of the above, gain unauthorized access to any of the above, or disrupt any other person&rsquo;s use or enjoyment of any of the above;</span></li>
                <li class="c14 li-bullet-0"><span class="c5">attempt to, or harass, abuse, or harm of another person or entity, including our employees and service providers;</span></li>
                <li class="c14 li-bullet-0"><span class="c5">impersonate another user or otherwise misrepresent yourself;</span></li>
                <li class="c14 li-bullet-0"><span class="c5">take any action that imposes an unreasonable or disproportionately large load on our infrastructure; or detrimentally interfere with, intercept, or expropriate any system, data, or information.</span></li>
              </ul>
              <h2 class="c3" id="h.yaozrl6tnkk"><span class="c8">13. General Information</span></h2>
              <h3 class="c2" id="h.wcay4awpq6di"><span class="c9">13.1 Entire Agreement</span></h3>
              <p class="c4"><span class="c5">This Agreement (and any additional terms, rules and conditions of participation that may be posted on the Site) constitute the entire agreement with respect to the Services and supersedes any prior agreements, oral or written. In the event of a conflict between this Agreement and the additional terms, rules and conditions of participation, the latter will prevail over the Agreement to the extent of the conflict.</span></p>
              <h3 class="c2" id="h.pz9xvkc37uro"><span class="c9">13.2 Waiver and Severability of the Agreement</span></h3>
              <p class="c4"><span class="c5">The failure of any entity to exercise or enforce any right or provision of the Agreement shall not constitute a waiver of such right or provision. If any provision of the Agreement is found by an arbitrator or court of competent jurisdiction to be invalid, the parties nevertheless agree that the arbitrator or court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the Agreement remain in full force and effect.</span></p>
              <h3 class="c2" id="h.81cxid8sqnon"><span class="c9">13.3 Section Titles</span></h3>
              <p class="c4"><span class="c5">The section titles in the Agreement are for convenience only and have no legal or contractual effect.</span></p>
              <h3 class="c2" id="h.9vaf4c2ogzh"><span class="c9">13.4 Privacy and Transparency</span></h3>
              <p class="c4"><span class="c5">Company respects the privacy of the Users.</span></p>
              <p class="c4"><span class="c5">The Company will treat any information about you in accordance with its Privacy Policy, which is incorporated herein by reference. The Privacy Policy provides an outline of the types of data and information about you we may collect or process, which you authorize by agreeing to these Terms of Service. You are asked to read the Privacy Policy before you use the Site or Services. If you are unwilling to accept the terms and conditions of the Privacy Policy, please do not use the Site and the Services.</span></p>
              <h3 class="c2" id="h.wibpb4baxc1p"><span class="c9">13.5 Conflict or Inconsistencies</span></h3>
              <p class="c4"><span class="c5">In the event of any conflict or inconsistency between this Terms of Service and any non-English language translation thereof, the terms and provisions of this Terms of Service shall control.</span></p>
              <h3 class="c2" id="h.45lpezv8nz1n"><span class="c9">13.6 Communications</span></h3>
              <p class="c4"><span class="c5">Company may utilize collected data and information about you, addressed above and in the Privacy Policy, for the purposes set out in the Privacy Policy</span></p>
              <p class="c4"><span class="c10">Users with questions, complaints or claims with respect to the Services may contact us using the relevant contact information set forth above and at legal@hover.engineering.</span></p>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style lang="scss" type="text/scss">
  .tos{
    background: $light-grey;
    min-height: calc(100vh - 4rem - 5px);
    .container{
      padding: 3rem 0;
    }
    .is-height-full{
      height: 100%;
    }
    .box{
      padding: 0;
      @include until($tablet){
        .sidebar{
          display: none;
          &.is-active{
            display: block;
          }
        }
      }
      .header{
        padding: 1rem 2rem;
        border-bottom: 2px solid $light-grey;
        @include until($tablet) {
          display: flex;
          align-items: center;
          justify-content: center;
          padding: .5rem 1rem;
          .title{
            margin-bottom: 0;
          }
        }
      }
      .sidebar{
        padding: 1rem;
        border-right: 2px solid $light-grey;
      }
      .docs-content{
        padding: 1rem;
        a{
          font-weight: bold;
        }
        .table{
          width: auto;
        }
      }
    }
  }
</style>
